apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system

---

apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  username: YWRtaW4=
  passphrase: YWRtaW4=